const COUNTRY = [
  { id: 1, name: "Australia", code: "AUS" },
  { id: 2, name: "Argentina", code: "ARG" },
  { id: 3, name: "Brazil", code: "BRA" },
  { id: 4, name: "Canada", code: "CAN" },
  { id: 5, name: "China", code: "CHN" },
  { id: 6, name: "France", code: "FRA" },
  { id: 7, name: "Germany", code: "DEU" },
  { id: 8, name: "India", code: "IND" },
  { id: 9, name: "Indonesia", code: "IDN" },
  { id: 10, name: "Italy", code: "ITA" },
  { id: 11, name: "Japan", code: "JPN" },
  { id: 12, name: "Mexico", code: "MEX" },
  { id: 13, name: "Russia", code: "RUS" },
  { id: 14, name: "South Africa", code: "ZAF" },
  { id: 15, name: "Spain", code: "ESP" },
  { id: 16, name: "United Kingdom", code: "GBR" },
  { id: 17, name: "United States", code: "USA" },
  { id: 18, name: "Turkey", code: "TUR" },
  { id: 19, name: "Thailand", code: "THA" },
  { id: 20, name: "Switzerland", code: "CHE" },
  { id: 21, name: "Sweden", code: "SWE" },
  { id: 22, name: "Saudi Arabia", code: "SAU" },
  { id: 23, name: "Portugal", code: "PRT" },
  { id: 24, name: "Poland", code: "POL" },
  { id: 25, name: "Norway", code: "NOR" },
  { id: 26, name: "Netherlands", code: "NLD" },
  { id: 27, name: "Malaysia", code: "MYS" },
  { id: 28, name: "Greece", code: "GRC" },
  { id: 29, name: "Egypt", code: "EGY" },
  { id: 30, name: "Denmark", code: "DNK" },
  { id: 31, name: "Czech Republic", code: "CZE" },
  { id: 32, name: "Chile", code: "CHL" },
  { id: 33, name: "Belgium", code: "BEL" },
  { id: 34, name: "Austria", code: "AUT" },
  { id: 35, name: "Vietnam", code: "VNM" },
  { id: 36, name: "Ukraine", code: "UKR" },
  { id: 37, name: "Taiwan", code: "TWN" },
  { id: 38, name: "Singapore", code: "SGP" },
  { id: 39, name: "New Zealand", code: "NZL" },
  { id: 40, name: "Israel", code: "ISR" },
  { id: 41, name: "Ireland", code: "IRL" },
  { id: 42, name: "Hungary", code: "HUN" },
  { id: 43, name: "Hong Kong", code: "HKG" },
  { id: 44, name: "Finland", code: "FIN" },
  { id: 45, name: "Philippines", code: "PHL" },
  { id: 46, name: "Pakistan", code: "PAK" },
  { id: 47, name: "Nigeria", code: "NGA" },
];

export default COUNTRY;
